spring:
    jms:
        template:
            default-destination: library.books.queue
    artemis:
        host: localhost
        port: 61616
        user: davidepravata
        password: dp
        embedded:
            enabled: false